### ISSUE TITLE
Custom 3D object format

### ISSUE THREAD

**Issue by Saticmotion** [wortelstoemp/BlackMesaResearch#8]

**Comment by wortelstoemp** [comment]
File spec currently is like so:

// Quareme-Verbeke Mesh (QVM File)

// NOTE: Always use spaces after a ',' and only triangles allowed!

// Vertices: v(x, y, z)
v(1.000000, 1.000000, 0.000000)
v(-1.000000, 1.000000, 0.000000)
v(-1.000000, -1.000000, 0.000000)
v(1.000000, -1.000000, 0.000000)

// Texture coordinates: t(u, v)
t(1.000000, 1.000000)
t(0.000000, 1.000000)
t(0.000000, 0.000000)
t(1.000000, 0.000000)

// Normals: n(x, y, z)
n(0.000000, 0.000000, 1.000000)

// Polygons: p(v(#, #, #), t(#, #, #), n(#))
// We always use triangles so only 1 normal per polygon needed
p(v(0, 1, 2), t(0, 1, 2), n(0))
p(v(2, 3, 0), t(2, 3, 0), n(0))

**Comment by wortelstoemp** [comment]
Works and is tested!
